development:
  adapter: postgresql
  encoding: unicode
  database: cloud_school_development
  host: localhost
  pool: 5
  username: saasbook
  password: saasbook

test:
  adapter: postgresql
  encoding: unicode
  database: cloud_school_test
  host: localhost
  pool: 5
  username: saasbook
  password: saasbook
